import { z } from "zod";

/**
 * Session identifier: a UUID v7 string. Time-ordered, so lexicographic order
 * matches creation order. Generated by the daemon (Bun.randomUUIDv7()).
 */
export const SessionIdSchema = z.uuidv7();
export type SessionId = z.infer<typeof SessionIdSchema>;

/**
 * The agent backend driving a session. M1 ships exactly one; M4 widens this
 * to an enum (codex-acp, gemini, native loop).
 */
export const BackendIdSchema = z.literal("claude-acp");
export type BackendId = z.infer<typeof BackendIdSchema>;

/**
 * How a session was opened. M1 has interactive only; review lands with the
 * GitHub App milestone.
 */
export const SessionModeSchema = z.literal("interactive");
export type SessionMode = z.infer<typeof SessionModeSchema>;

export const SessionStatusSchema = z.enum([
  "idle",
  "running",
  "waiting_for_permission",
  "closed",
]);
export type SessionStatus = z.infer<typeof SessionStatusSchema>;

/** Timestamps are ISO 8601 UTC strings (new Date().toISOString()). */
export const TimestampSchema = z.iso.datetime();
export type Timestamp = z.infer<typeof TimestampSchema>;

/**
 * One session as stored by the daemon. `id` is monad's own session id, the
 * one clients see. `agentSessionId` is the vendor adapter's session id,
 * stored so the daemon can ask the vendor to restore context after a
 * restart (vendor session/load).
 */
export const SessionRecordSchema = z.object({
  id: SessionIdSchema,
  cwd: z.string(),
  backend: BackendIdSchema,
  agentSessionId: z.string().optional(),
  mode: SessionModeSchema,
  status: SessionStatusSchema,
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
});
export type SessionRecord = z.infer<typeof SessionRecordSchema>;
