import { z } from "zod";

/**
 * Session identifier: a UUID v7 string. Time-ordered, so lexicographic order
 * matches creation order. Generated by the daemon (Bun.randomUUIDv7()).
 */
export const SessionIdSchema = z.uuidv7();
export type SessionId = z.infer<typeof SessionIdSchema>;

/**
 * The agent backend driving a session. M1 ships exactly one; M4 widens this
 * to an enum (codex-acp, gemini, native loop).
 */
export const BackendIdSchema = z.literal("claude-acp");
export type BackendId = z.infer<typeof BackendIdSchema>;

/**
 * How a session is being driven. interactive is M1's terminal loop; review
 * and fix are M2's PR-review modes (read-only policy, then worktree-scoped
 * edit policy). Stored on the record and switchable via monad attach --mode.
 */
export const SessionModeSchema = z.enum(["interactive", "review", "fix"]);
export type SessionMode = z.infer<typeof SessionModeSchema>;

/**
 * PR metadata pinned to a review session, resolved once via gh pr view when
 * the review starts. baseSha is the computed merge base, not the branch tip.
 */
export const SessionPrSchema = z.object({
  /** owner/name, e.g. "AaronCx/monad". */
  repo: z.string(),
  number: z.number().int().positive(),
  url: z.string(),
  headSha: z.string(),
  baseRef: z.string(),
  baseSha: z.string(),
  title: z.string(),
});
export type SessionPr = z.infer<typeof SessionPrSchema>;

export const SessionStatusSchema = z.enum([
  "idle",
  "running",
  "waiting_for_permission",
  "closed",
]);
export type SessionStatus = z.infer<typeof SessionStatusSchema>;

/** Timestamps are ISO 8601 UTC strings (new Date().toISOString()). */
export const TimestampSchema = z.iso.datetime();
export type Timestamp = z.infer<typeof TimestampSchema>;

/**
 * One session as stored by the daemon. `id` is monad's own session id, the
 * one clients see. `agentSessionId` is the vendor adapter's session id,
 * stored so the daemon can ask the vendor to restore context after a
 * restart (vendor session/load).
 */
export const SessionRecordSchema = z.object({
  id: SessionIdSchema,
  cwd: z.string(),
  backend: BackendIdSchema,
  agentSessionId: z.string().optional(),
  mode: SessionModeSchema,
  status: SessionStatusSchema,
  /**
   * Diff bounds for the session's checks binding. Review sessions (M2 stage
   * 3) pin them to the PR's base and head shas; interactive sessions leave
   * them unset, so run_checks diffs against the default-branch merge-base
   * at call time.
   */
  base: z.string().optional(),
  head: z.string().optional(),
  /** Present on review/fix sessions: the PR under review. */
  pr: SessionPrSchema.optional(),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
});
export type SessionRecord = z.infer<typeof SessionRecordSchema>;
